/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lox;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        Scanner classUnderTest = new Scanner("+");
        assertNotNull(classUnderTest.scanTokens());
    }
}
