/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lox;

import java.io.ByteArrayOutputStream;
import java.io.FileDescriptor;
import java.io.FileOutputStream;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;

public class templateClass {
    private ByteArrayOutputStream outContent = new ByteArrayOutputStream();
    private ByteArrayOutputStream errContent = new ByteArrayOutputStream();
    private final String baseDir = "src/test/resources/";

    protected String[] argGen(String fileName, Boolean debug) {
        List<String> args = new ArrayList<>();
        args.add(baseDir + fileName);

        if (Boolean.TRUE.equals(debug)) {
            args.add("--debug");
        }

        return args.toArray(new String[0]);
    }

    protected String[] argGen(String fileName) {
        return argGen(fileName, false);
    }

    /**
     * Turns on stdOut output capture
     */
    protected void captureOut() {
        outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));
    }

    /**
     * Turns on stdErr output capture
     */
    protected void captureErr() {
        errContent = new ByteArrayOutputStream();
        System.setErr(new PrintStream(errContent));
    }

    /**
     * Turns off stdOut capture and returns the contents
     * that have been captured
     *
     * @return
     */
    protected String getOut() {
        System.setOut(new PrintStream(new FileOutputStream(FileDescriptor.out)));
        return outContent.toString().replaceAll("\r", "");

    }

    /**
     * Turns off stdErr capture and returns the contents
     * that have been captured
     *
     * @return
     */
    protected String getErr() {
        System.setErr(new PrintStream(new FileOutputStream(FileDescriptor.out)));
        return errContent.toString().replaceAll("\r", "");
    }

}
